version: '3.8'

volumes:
  pg_data_production:
  backend_static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: s418963/taski_backend:latest
    depends_on: 
      - db
    env_file: .env
    volumes:
      - backend_static:/app/collected_static
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn taski.wsgi:application --bind 0.0.0.0:8000"
  
  frontend:  
    image: s418963/taski_frontend:latest
    volumes:
      - backend_static:/app/build 
    command: cp -r /app/build/. /app/build/
  
  gateway:
    image: s418963/taski_gateway:latest
    env_file: .env
    depends_on:
      - backend
      - frontend 
    ports:
      - "8080:80"
    volumes:
      - backend_static:/app/static