
volumes:
  pg_data_production:
  static_volume:
  frontend_build:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: s418963/taski_backend:latest
    depends_on: 
      - db
    env_file: .env
    volumes:
      - static_volume:/app/static
    
  frontend:  
    image: s418963/taski_frontend:latest
    volumes:
      - frontend_build:/app/build
    
  gateway:
    image: s418963/taski_gateway:latest
    env_file: .env
    depends_on:
      - backend
      - frontend 
    ports:
      - "8080:80"
    volumes:
      - static_volume:/static
      - frontend_build:/frontend_build